server:
  port: 10090

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #匹配所有请求
            allowCredentials: true
            allowedOrigins: "*" #允许所有域
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTION
              - PATCH
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      httpclient:
        connect-timeout: 10000
        response-timeout: 8s
      routes:
        # 搜索服务
        - id: search-web # 当前路由的标识
          uri: lb://search-web # lb指的是从注册中心中按照名称获取微服务,并遵循负载均衡策略
          predicates:
            - Path=/pin/**
        # 用户服务
        - id: user-web
          uri: lb://user-web
          predicates:
            - Path=/using/**
        # 管理员服务
        - id: admin-server
          uri: lb://admin-server
          predicates:
            - Path=/admin/**

logging:
  level:
    com.kuaipin.gateway: debug